New version of rmate

diff --git a/plugins/rmate/bin/rmate b/plugins/rmate/bin/rmate
--- a/plugins/rmate/bin/rmate
+++ b/plugins/rmate/bin/rmate
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # rmate
-# Copyright (C) 2011-2014 by Harald Lapp <harald@octris.org>
+# Copyright (C) 2011-2015 by Harald Lapp <harald@octris.org>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -33,8 +33,8 @@
 
 # init
 #
-version="0.9.1"
-version_date="2014-09-06"
+version="0.9.3"
+version_date="2015-03-03"
 version_string="rmate-sh $version ($version_date)"
 
 # determine hostname
@@ -76,7 +76,7 @@ function load_config {
     fi
 }
 
-for i in "/etc/${0##*/}" ~/."${0##*/}.rc"; do
+for i in "/etc/${0##*/}" ~/."${0##*/}/${0##*/}.rc" ~/."${0##*/}.rc"; do
     load_config $i
 done
 
@@ -123,7 +123,7 @@ function log {
 }
 
 function dirpath {
-  (cd `dirname $1`; pwd -P)
+    (cd `dirname $1` >/dev/null 2>/dev/null; pwd -P)
 }
 
 function canonicalize {
@@ -193,7 +193,7 @@ while test "${1:0:1}" = "-"; do
             exit 1
             ;;
     esac
-    
+
     shift
 done
 
@@ -212,6 +212,11 @@ fi
 if [ "$filepath" != "-" ]; then
     realpath=`canonicalize "$filepath"`
     log $realpath
+
+    if [ -d "$filepath" ]; then
+        echo "$filepath is a directory and rmate is unable to handle directories."
+        exit 1
+    fi
 
     if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
         if [[ $force = false ]]; then
@@ -320,7 +325,7 @@ if [ "$filetype" != "" ]; then
 fi
 
 if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
-    filesize=`ls -lL "$realpath" | awk '{print $5}'`
+    filesize=`ls -lLn "$realpath" | awk '{print $5}'`
     echo "data: $filesize" 1>&3
     cat "$realpath" 1>&3
 elif [ "$filepath" = "-" ]; then
